FROM alpine:3.14

ENV IS_CONTAINERIZED=true
ENV IS_FULL_DISK_SUPPORTED=false

RUN \
 echo "**** install build packages ****" && \
 apk add --no-cache --virtual=build-dependencies \
	g++ \
	py3-pip \
	python3-dev
RUN \
 echo "**** install runtime packages ****" && \
 apk add --no-cache --upgrade \
	ffmpeg \
	mediainfo \
	python3 \
	mktorrent \
	unrar