FROM gg-bot-base:disk-latest AS GIT_CLONER

WORKDIR /app

# add local files
COPY requirements/requirements.txt .
RUN \
  echo "**** install pip packages ****" && \
  pip install -r requirements.txt && \
  pip freeze > requirements.txt

COPY . .
RUN rm -r requirements/
RUN rm auto_reupload.py && chmod +x auto_upload.py

# ports and volumes
VOLUME /data /temp_upload

ENTRYPOINT [ "python3", "auto_upload.py"]
